name: This is my Sample project for Github Actions
on: push

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: run python application
        run: python my-app.py
        
      - name: Docker installation
        run: |
            sudo apt update
            sudo apt install apt-transport-https ca-certificates curl software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt install docker-ce
            sudo systemctl status docker
            sudo usermod -aG docker $USER

      - name: Check the Docker version
        run: sudo docker --version
    
      - name: Print the statement
        run: echo "my dear friend"
      
      - name: Testing
        run: echo "Testing is done"
