name: This is my Hello World Program

on:
  push:
    branches:
      - main    #triggers the action when it is pushed into main branch

  pull_request:
    branches:
      - main  #Triggers the action when the pull request is triggered.

jobs:
  build:
    runs-on: ubuntu-latest   #The type of runner the job will run on
    steps:  #The sequence of tasks will executed on the ubuntu machine
     

      - name: Print Hellow World for naveen
        run: echo "Hello This is Naveen Varma"
