name: This is my Sample project for Github Actions
on: push

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: run python application
        run: python my-app.py
        
      - name: Docker installation
        run: |
            sudo apt update
            sudo apt install apt-transport-https ca-certificates curl software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt install docker-ce
            sudo systemctl status docker
            sudo usermod -aG docker $USER

      - name: Docker Image build
        run: docker build -t myimage:latest .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
     
              
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: naveen.it2017@gmail.com
          password: Saii@2025

      - name: DockerHub Push
        run: docker image ls

              

