name: This is my Sample project for Github Actions
on: push

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: run python application
        run: python my-app.py
        
      - name: Docker installation
        run: sudo apt-get install docker.io

      - name: Check the Docker version
        run: docker --version
    
      - name: Print the statement
        run: echo "my dear friend"
      
      - name: Testing
        run: echo "Testing is done"
